[source]
name = "debber"
maintainer = "Alexandar Yovchev <alexyov@protonmail.com>"
section = "tools"
priority = "optional"
standards-version = "4.7.0"
rules = "#!/usr/bin/make -f"

[[packages]]
name = "debber"
arch = "amd64"
section = "tools"
priority = "optional"
description = "Simple debian package generator"

[[packages]]
name = "debber-help"
arch = "amd64"
section = "tools"
priority = "optional"
description = "Simple debian package generator - helper content"
