[source]
name = "debber"
maintainer = "Alexandar Yovchev <alexyov@protonmail.com>"
section = "tools"
priority = "optional"
standards-version = "4.7.0"
raw_rules = """#!/usr/bin/make -f

%:
	dh $@
override_dh_auto_build:
	GOOS=linux go build -ldflags "-s -w" -o debber cmd/debber/main.go
override_dh_install:
	dh_install debber usr/bin/
"""
[[source.changelog]]
version = "0.1.0"
distribution = ["bookworm"]
urgency = "low"
changes = [
    "This is a new feature for the package",
    "This is a bug fix for the package",
]
changed_by = "Alexandar Yovchev <alexyov@protonmail.com>"
date = "Mon, 10 Aug 2025 23:01:23 +0000"

[[source.changelog]]
version = "0.1.1"
distribution = ["bookworm"]
urgency = "low"
changes = ["This is a bugfix"]
changed_by = "Alexandar Yovchev <alexyov@protonmail.com>"
date = "Mon, 10 Aug 2025 23:05:23 +0000"

[source.copyright]
source = "<url://example.com>"
upstream_name = "debber"
upstream_contact = "Firstname Lastname <email@domain.com>"

[[source.copyright.files]]
files = "*"
copyright = ["2025, Alexandar Yovchev"]
license = "Apache-2.0"

[[source.copyright.files]]
files = "debian/"
copyright = ["2025, Alexandar Yovchev"]
license = "GPL-2+"

[[packages]]
name = "debber"
arch = "amd64"
section = "tools"
priority = "optional"
description = "Simple debian package generator"

[[packages]]
name = "debber-help"
arch = "amd64"
section = "tools"
priority = "optional"
description = "Simple debian package generator - helper content"
