[source]
name = "debber"
maintainer = "Alexandar Yovchev <alexyov@protonmail.com>"
section = "tools"
priority = "optional"
standards-version = "4.7.0"
raw_rules = """#!/usr/bin/make -f

%:
	dh $@
alex:
	@echo "is testing something"
"""

[[packages]]
name = "debber"
arch = "amd64"
section = "tools"
priority = "optional"
description = "Simple debian package generator"

[[packages]]
name = "debber-help"
arch = "amd64"
section = "tools"
priority = "optional"
description = "Simple debian package generator - helper content"
